// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/analyzer": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/analyzer" | "/about" | "/*";
  };
  "routes/[analyzer]._index.jsx": {
    id: "routes/[analyzer]._index";
    page: "/analyzer";
  };
  "routes/[about]._index.jsx": {
    id: "routes/[about]._index";
    page: "/about";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/[404]._index.jsx": {
    id: "routes/[404]._index";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/[analyzer]._index": typeof import("./app/routes/[analyzer]._index.jsx");
  "routes/[about]._index": typeof import("./app/routes/[about]._index.jsx");
  "routes/_index": typeof import("./app/routes/_index.jsx");
  "routes/[404]._index": typeof import("./app/routes/[404]._index.jsx");
};